version: "3"
services:

  jenkins:
    container_name: jenkins
    build: ./jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - jenkins_home:/var/jenkins_home

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  jenkins_home: