# -*- mode: ruby -*-
# # vi: set ft=ruby :
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Create box
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "box-cutter/ubuntu1404-desktop"
    config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.hostname = "ubuntu"
        
        # VirtualBox configuration
        ubuntu.vm.provider "virtualbox" do |vb|
            vb.name = "ubuntu.vm"
            vb.gui = true
            vb.memory = 1024
        end
    end
end